name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 12 * * 4'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Set up cargo cache
        uses: actions/cache@v3
        continue-on-error: false
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose

      - name: Build linter
        run: cargo build --example lint

      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          name: bin
          path: target/debug/examples/lint

  test-compatibility:
    needs: build
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/download-artifact@v3

      - name: Clone stalkerware-indicators repo
        run: git clone --depth=1 https://github.com/AssoEchap/stalkerware-indicators

      - name: Lint ioc.yaml
        run: chmod +x ./bin/lint && ./bin/lint stalkerware-indicators/ioc.yaml
